version: '3.8'

services:
  app:
    build: 
    container_name: bookstore-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: bookstore
      SECRET_KEY: ${SECRET_KEY}
      TOKEN_ISSUER: ${TOKEN_ISSUER}
      TOKEN_AUDIENCE: ${TOKEN_AUDIENCE}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
  
  postgres:
    image: postgres:15-alphine
    container_name: bookstore-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookstore
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    restart: unless-stopped
volumes:
  postgres_data: